apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "two-tier-app.fullname" . }}-mysql-pvc
  labels:
    {{- include "two-tier-app.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.mysql.persistence.storageClass }}
  storageClassName: {{ .Values.mysql.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size }}
