apiVersion: v1
kind: Secret
metadata:
  name: {{ include "two-tier-app.fullname" . }}-secret
  labels:
    {{- include "two-tier-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.secret.rootPassword | quote }}
  MYSQL_PASSWORD: {{ .Values.secret.userPassword | quote }}
